name: "Testing the CPU stuff"
on:
  push:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Getting the sources"
      uses: actions/checkout@master
    - name: "Building the libraries"
      run: make -j8
    - name: "Running tests"
      run: make test TESTS="6502"
